//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Applicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicant()
        {
            this.ApplPayment = new HashSet<ApplPayment>();
        }
    
        public int ID { get; set; }
        public int REG_ID { get; set; }
        public int VAC_ID { get; set; }
        [DisplayName("Age")]
        [Required(ErrorMessage="Age is not secified")]
        public int AGE { get; set; }
        [DisplayName("Sex")]
        [Required(ErrorMessage = "Sex is not selected")]
        public string SEX { get; set; }
        [DisplayName("Qualifcation")]
        [Required(ErrorMessage = "This field is required")]
        public string QUALIFICATION { get; set; }
        [DisplayName("Experiance")]
        [Required(ErrorMessage = "Experiance is required")]
        public int EXPERIENCE { get; set; }
        [DisplayName("Kebele identification")]
        [Required(ErrorMessage = "Kebele id is required")]
        public byte[] KEBELEID { get; set; }
        [DisplayName("CV")]
        [Required(ErrorMessage = "CV is required")]
        public byte[] CV { get; set; }
        [DisplayName("Descrption")]
        
        public string DESCRPTION { get; set; }
        [DisplayName("Remark")]
        [Required(ErrorMessage = "Remark is not checked")]
        public bool REMARK { get; set; }
    
        public virtual Register Register { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplPayment> ApplPayment { get; set; }
    }
}
