//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public int REG_ID { get; set; }
        public string COMMENT1 { get; set; }
        public byte[] RECEIVEDDATE { get; set; }
    
        public virtual Register Register { get; set; }
    }
}
