//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompaPayment = new HashSet<CompaPayment>();
            this.Vacancy = new HashSet<Vacancy>();
        }
    
        public int ID { get; set; }
        public int REG_ID { get; set; }
        [DisplayName("Company name")]
        [Required(ErrorMessage = "Company name is not filled")]
        public string COMP_NAME { get; set; }
        [DisplayName("Company owner")]
        [Required(ErrorMessage = "Owner is not filled")]
        public string OWNERS { get; set; }
        [DisplayName("Region of Company")]
        [Required(ErrorMessage = "Region is not filled")]
        public string REGION { get; set; }
        [DisplayName("Zone")]
        [Required(ErrorMessage = "Zone is not filled")]
        public string ZONE { get; set; }
        [DisplayName("Town")]
        [Required(ErrorMessage = "Town is not filled")]
        public string TOWN { get; set; }
        [DisplayName("Kebele")]
        [Required(ErrorMessage = "Kebele is not filled")]
        public string KEBELE { get; set; }
        [DisplayName("Phone number")]
        [Required(ErrorMessage = "Phone is not filled")]
        [DataType(DataType.PhoneNumber)]
        public string PHONE { get; set; }
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email is not filled")]
        public string EMAIL { get; set; }
        [DisplayName("Descrption")]
      
        public string DESCRPTION { get; set; }
        [DisplayName("Status")]
      
        public bool STATUS { get; set; }
        [DisplayName("Remark")]
        
        public Nullable<bool> REMARK { get; set; }
    
        public virtual Register Register { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompaPayment> CompaPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacancy> Vacancy { get; set; }
    }
}
