//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobBrokerEntities : DbContext
    {
        public JobBrokerEntities()
            : base("name=JobBrokerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Applicant> Applicant { get; set; }
        public virtual DbSet<ApplPayment> ApplPayment { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompaPayment> CompaPayment { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Register> Register { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Vacancy> Vacancy { get; set; }
    }
}
