//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partnership
    {
        public int ID { get; set; }
        public string PARTNERNAME { get; set; }
        public string EMAILADD { get; set; }
        public string PHONE { get; set; }
        public string PROFESSION { get; set; }
        public string SUPPORT { get; set; }
        public Nullable<decimal> BROKER_ACCNO { get; set; }
        public string BROKER_MAIL { get; set; }
        public byte[] REGdate { get; set; }
    }
}
