//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Register()
        {
            this.Applicant = new HashSet<Applicant>();
            this.Comment = new HashSet<Comment>();
            this.Company = new HashSet<Company>();
        }
    
        public int ID { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string REGION { get; set; }
        public string ZONE { get; set; }
        public string TOWN { get; set; }
        public string KEBELE { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string SEX { get; set; }
        public System.DateTime DOB { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
       
        public string QUEST { get; set; }
        public string ANS { get; set; }
        public byte[] PICTURE { get; set; }
        public string ROLE { get; set; }
        public byte[] REGDATE { get; set; }
        public Nullable<System.DateTime> ACCEXPDATE { get; set; }
        public bool STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicant> Applicant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Company { get; set; }
        public string LoginErrorMsg { get; internal set; }
        public string NewPassword { get; set; }
    }
}
