//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public Nullable<int> DATE { get; set; }
        public Nullable<int> NUM_REG { get; set; }
        public Nullable<int> NUM_COMP { get; set; }
        public Nullable<int> NUM_JOB { get; set; }
        public Nullable<int> NUM_APP { get; set; }
        public Nullable<int> NUM_PAID_APP { get; set; }
        public Nullable<int> NUM_PAID_COMP { get; set; }
        public Nullable<int> NUM_VAC { get; set; }
        public Nullable<int> NUM_COMM { get; set; }
        public Nullable<int> NUM_NEWS { get; set; }
        public bool REMARK { get; set; }
    }
}
