//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Vacancy
    {
        public int ID { get; set; }
        public int COMP_ID { get; set; }
        public int JOB_ID { get; set; }
        [DisplayName("Minimum qualification")]
        [Required(ErrorMessage="Qualification is required")]
        public string MIN_QUALF { get; set; }
        public byte[] POSTDATE { get; set; }
        [DisplayName("Interview date")]
        [Required(ErrorMessage = "Interview date is required")]
        [DataType(DataType.Date)]
        public System.DateTime INTERVDATE { get; set; }
        [DisplayName("Interview time")]
        [Required(ErrorMessage = "Interview time is required")]
        [DataType(DataType.Time)]
        public System.TimeSpan INTERVTIME { get; set; }
        [DisplayName("Job Duration")]
        [Required(ErrorMessage = "Duration is required")]
       
        public string DURATION { get; set; }
        [DisplayName("Salary amount")]
        [Required(ErrorMessage = "Salary is required")]
        [DataType(DataType.Currency)]
        public decimal SALARY { get; set; }
        [DisplayName("Required number")]
        [Required(ErrorMessage = "this field is required")]
       
        public int REQ_NUM { get; set; }
        [DisplayName("Sex")]
        [Required(ErrorMessage = "Sex is not selected")]
      
        public string REQ_SEX { get; set; }
        [DisplayName("Descrption")]
       
        public string DESCRPTION { get; set; }
        [DisplayName("Status")]
        [Required(ErrorMessage = "Status is not checked")]
        public bool STATUS { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Job Job { get; set; }
    }
}
